{% set name = "types-pytz" %}
{% set version = "2021.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pytz-{{ version }}.tar.gz
  sha256: 86a61967834dceeaaf98b6902ed8357efdd262bb8afcaf4bc8ccecf748592778

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pytz-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pytz
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
