{% set name = "types-pytz" %}
{% set version = "2022.2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pytz-{{ version }}.tar.gz
  sha256: 47cfb19c52b9f75896440541db392fd312a35b279c6307a531db71152ea63e2b
  skip: True # [py<36]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - test -f $SP_DIR/pytz-stubs/__init__.pyi # [not win]
    - if not exist %SP_DIR%\pytz-stubs\__init__.pyi exit 1 # [win]


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pytz
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
