{% set name = "types-pytz" %}
{% set version = "2026.1.1.20260304" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0c3542d8e9b0160b424233440c52b83d6f58cae4b85333d54e4f961cf013e117

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - test -f $SP_DIR/pytz-stubs/__init__.pyi  # [not win]
    - if not exist %SP_DIR%\pytz-stubs\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pytz
  license: Apache-2.0 AND MIT
  license_family: Other
  license_file: LICENSE
  dev_url: https://github.com/python/typeshed
  doc_url: https://typing.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
