{% set name = "types-pytz" %}
{% set version = "2025.2.0.20250809" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types_pytz-{{ version }}.tar.gz
  sha256: 222e32e6a29bb28871f8834e8785e3801f2dc4441c715cd2082b271eecbe21e5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/pytz-stubs/__init__.pyi  # [not win]
    - if not exist %SP_DIR%\pytz-stubs\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pytz
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  dev_url: https://github.com/python/typeshed
  doc_url: https://typing.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
